package com.acme.application.group_a.shared.awt;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.form.AbstractFormData;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;
import org.eclipse.scout.rt.shared.data.form.properties.AbstractPropertyData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications
 * recommended.
 */
@Generated(value = "com.acme.application.group_a.client.awt.ProduktForm", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class ProduktFormData extends AbstractFormData {

	private static final long serialVersionUID = 1L;

	public Active getActive() {
		return getFieldByClass(Active.class);
	}

	public BestandMin getBestandMin() {
		return getFieldByClass(BestandMin.class);
	}

	public Bezeichnung getBezeichnung() {
		return getFieldByClass(Bezeichnung.class);
	}

	/**
	 * access method for property Id.
	 */
	public String getId() {
		return getIdProperty().getValue();
	}

	/**
	 * access method for property Id.
	 */
	public void setId(String id) {
		getIdProperty().setValue(id);
	}

	public IdProperty getIdProperty() {
		return getPropertyByClass(IdProperty.class);
	}

	public Nr getNr() {
		return getFieldByClass(Nr.class);
	}

	public ProdArt getProdArt() {
		return getFieldByClass(ProdArt.class);
	}

	public ProdFamilie getProdFamilie() {
		return getFieldByClass(ProdFamilie.class);
	}

	public static class Active extends AbstractValueFieldData<Boolean> {

		private static final long serialVersionUID = 1L;
	}

	public static class BestandMin extends AbstractValueFieldData<Long> {

		private static final long serialVersionUID = 1L;
	}

	public static class Bezeichnung extends AbstractValueFieldData<String> {

		private static final long serialVersionUID = 1L;
	}

	public static class IdProperty extends AbstractPropertyData<String> {

		private static final long serialVersionUID = 1L;
	}

	public static class Nr extends AbstractValueFieldData<Long> {

		private static final long serialVersionUID = 1L;
	}

	public static class ProdArt extends AbstractValueFieldData<String> {

		private static final long serialVersionUID = 1L;
	}

	public static class ProdFamilie extends AbstractValueFieldData<String> {

		private static final long serialVersionUID = 1L;
	}
}
