package com.acme.application.group_a.shared.awt;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.form.AbstractFormData;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;
import org.eclipse.scout.rt.shared.data.form.properties.AbstractPropertyData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications
 * recommended.
 */
@Generated(value = "com.acme.application.group_a.client.awt.PruefkoerperForm", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class PruefkoerperFormData extends AbstractFormData {

	private static final long serialVersionUID = 1L;

	public Active getActive() {
		return getFieldByClass(Active.class);
	}

	public Bestand getBestand() {
		return getFieldByClass(Bestand.class);
	}

	public Boxe getBoxe() {
		return getFieldByClass(Boxe.class);
	}

	public Breite getBreite() {
		return getFieldByClass(Breite.class);
	}

	public Color getColor() {
		return getFieldByClass(Color.class);
	}

	public ColorDescription getColorDescription() {
		return getFieldByClass(ColorDescription.class);
	}

	public Dicke getDicke() {
		return getFieldByClass(Dicke.class);
	}

	public Form getForm() {
		return getFieldByClass(Form.class);
	}

	/**
	 * access method for property Id.
	 */
	public String getId() {
		return getIdProperty().getValue();
	}

	/**
	 * access method for property Id.
	 */
	public void setId(String id) {
		getIdProperty().setValue(id);
	}

	public IdProperty getIdProperty() {
		return getPropertyByClass(IdProperty.class);
	}

	public Laenge getLaenge() {
		return getFieldByClass(Laenge.class);
	}

	public Nr getNr() {
		return getFieldByClass(Nr.class);
	}

	public Produkt getProdukt() {
		return getFieldByClass(Produkt.class);
	}

	public Schank getSchank() {
		return getFieldByClass(Schank.class);
	}

	public static class Active extends AbstractValueFieldData<Boolean> {

		private static final long serialVersionUID = 1L;
	}

	public static class Bestand extends AbstractValueFieldData<Long> {

		private static final long serialVersionUID = 1L;
	}

	public static class Boxe extends AbstractValueFieldData<String> {

		private static final long serialVersionUID = 1L;
	}

	public static class Breite extends AbstractValueFieldData<Long> {

		private static final long serialVersionUID = 1L;
	}

	public static class Color extends AbstractValueFieldData<String> {

		private static final long serialVersionUID = 1L;
	}

	public static class ColorDescription extends AbstractValueFieldData<String> {

		private static final long serialVersionUID = 1L;
	}

	public static class Dicke extends AbstractValueFieldData<Long> {

		private static final long serialVersionUID = 1L;
	}

	public static class Form extends AbstractValueFieldData<String> {

		private static final long serialVersionUID = 1L;
	}

	public static class IdProperty extends AbstractPropertyData<String> {

		private static final long serialVersionUID = 1L;
	}

	public static class Laenge extends AbstractValueFieldData<Long> {

		private static final long serialVersionUID = 1L;
	}

	public static class Nr extends AbstractValueFieldData<Long> {

		private static final long serialVersionUID = 1L;
	}

	public static class Produkt extends AbstractValueFieldData<String> {

		private static final long serialVersionUID = 1L;
	}

	public static class Schank extends AbstractValueFieldData<String> {

		private static final long serialVersionUID = 1L;
	}
}
