package com.acme.application.group_a.shared.awt;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.basic.table.AbstractTableRowData;
import org.eclipse.scout.rt.shared.data.page.AbstractTablePageData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications
 * recommended.
 */
@Generated(value = "com.acme.application.group_a.client.awt.PruefkoerperTablePage", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class PruefkoerperTablePageData extends AbstractTablePageData {

	private static final long serialVersionUID = 1L;

	@Override
	public PruefkoerperTableRowData addRow() {
		return (PruefkoerperTableRowData) super.addRow();
	}

	@Override
	public PruefkoerperTableRowData addRow(int rowState) {
		return (PruefkoerperTableRowData) super.addRow(rowState);
	}

	@Override
	public PruefkoerperTableRowData createRow() {
		return new PruefkoerperTableRowData();
	}

	@Override
	public Class<? extends AbstractTableRowData> getRowType() {
		return PruefkoerperTableRowData.class;
	}

	@Override
	public PruefkoerperTableRowData[] getRows() {
		return (PruefkoerperTableRowData[]) super.getRows();
	}

	@Override
	public PruefkoerperTableRowData rowAt(int index) {
		return (PruefkoerperTableRowData) super.rowAt(index);
	}

	public void setRows(PruefkoerperTableRowData[] rows) {
		super.setRows(rows);
	}

	public static class PruefkoerperTableRowData extends AbstractTableRowData {

		private static final long serialVersionUID = 1L;
		public static final String id = "id";
		public static final String nr = "nr";
		public static final String produkt = "produkt";
		public static final String produktFamilie = "produktFamilie";
		public static final String form = "form";
		public static final String color = "color";
		public static final String colorDescription = "colorDescription";
		public static final String schrank = "schrank";
		public static final String boxe = "boxe";
		public static final String laenge = "laenge";
		public static final String breite = "breite";
		public static final String dicke = "dicke";
		public static final String bestand = "bestand";
		public static final String bestandMin = "bestandMin";
		public static final String active = "active";
		private String m_id;
		private Integer m_nr;
		private String m_produkt;
		private String m_produktFamilie;
		private String m_form;
		private String m_color;
		private String m_colorDescription;
		private String m_schrank;
		private String m_boxe;
		private Integer m_laenge;
		private Integer m_breite;
		private Integer m_dicke;
		private Integer m_bestand;
		private Integer m_bestandMin;
		private Boolean m_active;

		public String getId() {
			return m_id;
		}

		public void setId(String newId) {
			m_id = newId;
		}

		public Integer getNr() {
			return m_nr;
		}

		public void setNr(Integer newNr) {
			m_nr = newNr;
		}

		public String getProdukt() {
			return m_produkt;
		}

		public void setProdukt(String newProdukt) {
			m_produkt = newProdukt;
		}

		public String getProduktFamilie() {
			return m_produktFamilie;
		}

		public void setProduktFamilie(String newProduktFamilie) {
			m_produktFamilie = newProduktFamilie;
		}

		public String getForm() {
			return m_form;
		}

		public void setForm(String newForm) {
			m_form = newForm;
		}

		public String getColor() {
			return m_color;
		}

		public void setColor(String newColor) {
			m_color = newColor;
		}

		public String getColorDescription() {
			return m_colorDescription;
		}

		public void setColorDescription(String newColorDescription) {
			m_colorDescription = newColorDescription;
		}

		public String getSchrank() {
			return m_schrank;
		}

		public void setSchrank(String newSchrank) {
			m_schrank = newSchrank;
		}

		public String getBoxe() {
			return m_boxe;
		}

		public void setBoxe(String newBoxe) {
			m_boxe = newBoxe;
		}

		public Integer getLaenge() {
			return m_laenge;
		}

		public void setLaenge(Integer newLaenge) {
			m_laenge = newLaenge;
		}

		public Integer getBreite() {
			return m_breite;
		}

		public void setBreite(Integer newBreite) {
			m_breite = newBreite;
		}

		public Integer getDicke() {
			return m_dicke;
		}

		public void setDicke(Integer newDicke) {
			m_dicke = newDicke;
		}

		public Integer getBestand() {
			return m_bestand;
		}

		public void setBestand(Integer newBestand) {
			m_bestand = newBestand;
		}

		public Integer getBestandMin() {
			return m_bestandMin;
		}

		public void setBestandMin(Integer newBestandMin) {
			m_bestandMin = newBestandMin;
		}

		public Boolean getActive() {
			return m_active;
		}

		public void setActive(Boolean newActive) {
			m_active = newActive;
		}
	}
}
