package com.acme.application.group_a.shared.sv;

import java.util.Date;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.basic.table.AbstractTableRowData;
import org.eclipse.scout.rt.shared.data.page.AbstractTablePageData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications
 * recommended.
 */
@Generated(value = "com.acme.application.group_a.client.sv.SicherungTablePage", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class SicherungTablePageData extends AbstractTablePageData {

	private static final long serialVersionUID = 1L;

	@Override
	public SicherungTableRowData addRow() {
		return (SicherungTableRowData) super.addRow();
	}

	@Override
	public SicherungTableRowData addRow(int rowState) {
		return (SicherungTableRowData) super.addRow(rowState);
	}

	@Override
	public SicherungTableRowData createRow() {
		return new SicherungTableRowData();
	}

	@Override
	public Class<? extends AbstractTableRowData> getRowType() {
		return SicherungTableRowData.class;
	}

	@Override
	public SicherungTableRowData[] getRows() {
		return (SicherungTableRowData[]) super.getRows();
	}

	@Override
	public SicherungTableRowData rowAt(int index) {
		return (SicherungTableRowData) super.rowAt(index);
	}

	public void setRows(SicherungTableRowData[] rows) {
		super.setRows(rows);
	}

	public static class SicherungTableRowData extends AbstractTableRowData {

		private static final long serialVersionUID = 1L;
		public static final String id = "id";
		public static final String gebaeude = "gebaeude";
		public static final String anlNr = "anlNr";
		public static final String anlage = "anlage";
		public static final String etage = "etage";
		public static final String standort = "standort";
		public static final String sicherung = "sicherung";
		public static final String if_ = "if";
		public static final String befund = "befund";
		public static final String pruefmethode = "pruefmethode";
		public static final String visum = "visum";
		public static final String datum = "datum";
		public static final String active = "active";
		private String m_id;
		private String m_gebaeude;
		private String m_anlNr;
		private String m_anlage;
		private String m_etage;
		private String m_standort;
		private String m_sicherung;
		private String m_if;
		private String m_befund;
		private String m_pruefmethode;
		private String m_visum;
		private Date m_datum;
		private Boolean m_active;

		public String getId() {
			return m_id;
		}

		public void setId(String newId) {
			m_id = newId;
		}

		public String getGebaeude() {
			return m_gebaeude;
		}

		public void setGebaeude(String newGebaeude) {
			m_gebaeude = newGebaeude;
		}

		public String getAnlNr() {
			return m_anlNr;
		}

		public void setAnlNr(String newAnlNr) {
			m_anlNr = newAnlNr;
		}

		public String getAnlage() {
			return m_anlage;
		}

		public void setAnlage(String newAnlage) {
			m_anlage = newAnlage;
		}

		public String getEtage() {
			return m_etage;
		}

		public void setEtage(String newEtage) {
			m_etage = newEtage;
		}

		public String getStandort() {
			return m_standort;
		}

		public void setStandort(String newStandort) {
			m_standort = newStandort;
		}

		public String getSicherung() {
			return m_sicherung;
		}

		public void setSicherung(String newSicherung) {
			m_sicherung = newSicherung;
		}

		public String getIf() {
			return m_if;
		}

		public void setIf(String newIf) {
			m_if = newIf;
		}

		public String getBefund() {
			return m_befund;
		}

		public void setBefund(String newBefund) {
			m_befund = newBefund;
		}

		public String getPruefmethode() {
			return m_pruefmethode;
		}

		public void setPruefmethode(String newPruefmethode) {
			m_pruefmethode = newPruefmethode;
		}

		public String getVisum() {
			return m_visum;
		}

		public void setVisum(String newVisum) {
			m_visum = newVisum;
		}

		public Date getDatum() {
			return m_datum;
		}

		public void setDatum(Date newDatum) {
			m_datum = newDatum;
		}

		public Boolean getActive() {
			return m_active;
		}

		public void setActive(Boolean newActive) {
			m_active = newActive;
		}
	}
}
