package com.acme.application.group_a.shared.sv;

import java.util.Date;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.form.AbstractFormData;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;
import org.eclipse.scout.rt.shared.data.form.properties.AbstractPropertyData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications
 * recommended.
 */
@Generated(value = "com.acme.application.group_a.client.sv.SicherungForm", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class SicherungFormData extends AbstractFormData {

	private static final long serialVersionUID = 1L;

	public Active getActive() {
		return getFieldByClass(Active.class);
	}

	public AnlNr getAnlNr() {
		return getFieldByClass(AnlNr.class);
	}

	public Anlage getAnlage() {
		return getFieldByClass(Anlage.class);
	}

	public Befund getBefund() {
		return getFieldByClass(Befund.class);
	}

	public Datum getDatum() {
		return getFieldByClass(Datum.class);
	}

	public Etage getEtage() {
		return getFieldByClass(Etage.class);
	}

	public GebNr getGebNr() {
		return getFieldByClass(GebNr.class);
	}

	/**
	 * access method for property Id.
	 */
	public String getId() {
		return getIdProperty().getValue();
	}

	/**
	 * access method for property Id.
	 */
	public void setId(String id) {
		getIdProperty().setValue(id);
	}

	public IdProperty getIdProperty() {
		return getPropertyByClass(IdProperty.class);
	}

	public If getIf() {
		return getFieldByClass(If.class);
	}

	public Pruefmethode getPruefmethode() {
		return getFieldByClass(Pruefmethode.class);
	}

	public Sicherung getSicherung() {
		return getFieldByClass(Sicherung.class);
	}

	public Standort getStandort() {
		return getFieldByClass(Standort.class);
	}

	public Visum getVisum() {
		return getFieldByClass(Visum.class);
	}

	public static class Active extends AbstractValueFieldData<Boolean> {

		private static final long serialVersionUID = 1L;
	}

	public static class AnlNr extends AbstractValueFieldData<String> {

		private static final long serialVersionUID = 1L;
	}

	public static class Anlage extends AbstractValueFieldData<String> {

		private static final long serialVersionUID = 1L;
	}

	public static class Befund extends AbstractValueFieldData<String> {

		private static final long serialVersionUID = 1L;
	}

	public static class Datum extends AbstractValueFieldData<Date> {

		private static final long serialVersionUID = 1L;
	}

	public static class Etage extends AbstractValueFieldData<String> {

		private static final long serialVersionUID = 1L;
	}

	public static class GebNr extends AbstractValueFieldData<String> {

		private static final long serialVersionUID = 1L;
	}

	public static class IdProperty extends AbstractPropertyData<String> {

		private static final long serialVersionUID = 1L;
	}

	public static class If extends AbstractValueFieldData<String> {

		private static final long serialVersionUID = 1L;
	}

	public static class Pruefmethode extends AbstractValueFieldData<String> {

		private static final long serialVersionUID = 1L;
	}

	public static class Sicherung extends AbstractValueFieldData<String> {

		private static final long serialVersionUID = 1L;
	}

	public static class Standort extends AbstractValueFieldData<String> {

		private static final long serialVersionUID = 1L;
	}

	public static class Visum extends AbstractValueFieldData<String> {

		private static final long serialVersionUID = 1L;
	}
}
